export const PROJECT_LIST_LOADING = "PROJECT_LIST_LOADING";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAILURE = "PROJECT_LIST_FAILURE";
export const PROJECT_TOGGLE = "PROJECT_TOGGLE";
