export const PROJECT_EDIT_LOADING = "PROJECT_EDIT_LOADING";
export const PROJECT_EDIT_SUCCESS = "PROJECT_EDIT_SUCCESS";
export const PROJECT_EDIT_FAILURE = "PROJECT_EDIT_FAILURE";
export const PROJECT_EDIT_TOGGLE = "PROJECT_EDIT_TOGGLE";
